"""add token_count duration_ms to chat_messages

Revision ID: 0bbee07c9ded
Revises: 819af331bc3d
Create Date: 2026-03-29 16:38:56.891326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbee07c9ded'
down_revision: Union[str, Sequence[str], None] = '819af331bc3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('token_count', sa.BigInteger(), nullable=True))
    op.add_column('chat_messages', sa.Column('duration_ms', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'duration_ms')
    op.drop_column('chat_messages', 'token_count')
    # ### end Alembic commands ###
