"""add ttf_ms to chat_messages

Revision ID: 65052451f239
Revises: 0bbee07c9ded
Create Date: 2026-03-29 16:59:43.577129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65052451f239'
down_revision: Union[str, Sequence[str], None] = '0bbee07c9ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('ttf_ms', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'ttf_ms')
    # ### end Alembic commands ###
